version: 0.2

# Environment variables
env:
# Local variables
  variables:
    TERRAGRUNT_DIR: "TERRAGRUNT" # Where you store your terragrunt environments
    TERRAGRUNT_ENVIRONMENT: "DEV" # Where you store yoru environment root terragrunt.hcl file
    CONFIG_FILES_PATH: "PIPELINE" # Where you store the configuration files for tflint, checkov and tfsec

# CodeBuild static variables:
  # S3_BUCKET: where to store the artifacts
  # ARTIFACTS_PREFIX: the folder name where to store the artifacts

# CloudWatch Events rule will also provide the following environment variables:
  # PULL_REQUEST_ID
  # SOURCE_COMMIT
  # DESTINATION_COMMIT
  # SOURCE_BRANCH
  # DESTINATION_BRANCH
  # ACCOUNT

phases:
  pre_build:
    commands:
      # Preparing build metadata
      - BUILD_NAME=$(echo $CODEBUILD_BUILD_ID | cut -d':' -f1)
      - BUILD_ID=$(echo $CODEBUILD_BUILD_ID | cut -d':' -f2)
      - BUILD_URL=$(echo \
          "https://$AWS_DEFAULT_REGION.console.aws.amazon.com/codesuite/codebuild/$ACCOUNT/projects/$BUILD_NAME/build/$BUILD_NAME%3A$BUILD_ID/?region=$AWS_DEFAULT_REGION")
      - export ARTIFACTS_URL=\
          "https://s3.console.aws.amazon.com/s3/buckets/$S3_BUCKET?region=$AWS_DEFAULT_REGION&prefix=$ARTIFACTS_PREFIX/$PULL_REQUEST_ID/$CODEBUILD_BUILD_NUMBER/&showversions=false" 
      # Pull Request comment: Build starting notification 
      - |
        aws codecommit post-comment-for-pull-request \
          --pull-request-id $PULL_REQUEST_ID \
          --repository-name $REPOSITORY_NAME \
          --before-commit-id $SOURCE_COMMIT \
          --after-commit-id $DESTINATION_COMMIT \
          --content "⚙️ Build '$BUILD_NAME' \#[$CODEBUILD_BUILD_NUMBER]($BUILD_URL) started."
      # Moving the code to a specific directory to avoid issue: https://github.com/gruntwork-io/terragrunt/issues/1565
      - mkdir /codebuild/output/code 
      - cp -la ${CODEBUILD_SRC_DIR}/. /codebuild/output/code
      - export CODEBUILD_SRC_DIR="/codebuild/output/code"


  build:
    commands:
      # Changing to the new location of the code defined in the prebuild stage
      - cd $CODEBUILD_SRC_DIR
      # Checking out the source branch of the pull request
      - git checkout $SOURCE_COMMIT 
      # Running Checkov, TFlint and TFsec against our terrafrom code 
      - checkov -d . --framework terraform --soft-fail > CHECKOV_REPORT.txt # Soft-fail will prevent the build from failing if errors are found
      - (cd $CONFIG_FILES_PATH && tflint --init) 
      - tflint --recursive > TFLINT_REPORT.txt || true # Soft-fail
      - tfsec . -f markdown > TFSEC_REPORT.md || true # Soft-fail
      # Initializing Terragrunt
      - cd $TERRAGRUNT_DIR/$TERRAGRUNT_ENVIRONMENT/
      # Fetching the terraform plan changes for all modules:
      - terragrunt run-all plan > TMP.txt
      # Cleaning up the Terragrunt apply output
      - sed -e 's/\x1b\[[0-9;]*m//g' $CODEBUILD_SRC_DIR/$TERRAGRUNT_DIR/$TERRAGRUNT_ENVIRONMENT/TMP.txt > $CODEBUILD_SRC_DIR/TERRAGRUNT_PLAN_REPORT.txt
      # Changing back to the code location
      - cd $CODEBUILD_SRC_DIR

  post_build:
    commands:
      # if the build is sucessful, we post a comment in the Pull request with the link to the Artifacts and we change the content of the var content accordingly
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then
          content="✔️ Build '$BUILD_NAME' \#[$CODEBUILD_BUILD_NUMBER]($BUILD_URL) succeeded."

          aws codecommit post-comment-for-pull-request \
            --pull-request-id $PULL_REQUEST_ID \
            --repository-name $REPOSITORY_NAME \
            --before-commit-id $SOURCE_COMMIT \
            --after-commit-id $DESTINATION_COMMIT \
            --content "📦 Build '$BUILD_NAME' \#$CODEBUILD_BUILD_NUMBER [Artifacts]($ARTIFACTS_URL) are ready."
        else
          content="❌ Build '$BUILD_NAME' \#[$CODEBUILD_BUILD_NUMBER]($BUILD_URL) failed."
        fi
      # Pull Request comment: Build information
      - |
        aws codecommit post-comment-for-pull-request \
          --pull-request-id $PULL_REQUEST_ID \
          --repository-name $REPOSITORY_NAME \
          --before-commit-id $DESTINATION_COMMIT \
          --after-commit-id $SOURCE_COMMIT \
          --content "$content"

artifacts:
  # We will store the resulting artifacts in $S3_BUCKET/$ARTIFACTS_PREFIX/$PULL_REQUEST_ID/$CODEBUILD_BUILD_NUMBER
  files:
    - "${CODEBUILD_SRC_DIR}/*REPORT*"
  name: $PULL_REQUEST_ID/$CODEBUILD_BUILD_NUMBER
  discard-paths: yes